export interface UserI {
    id: number,
    nombre: string,
    apellidos: string,
    curp: string,  
    nsegurosocial: string,
    rfc: string,
    domicilio:string,
    fechadeentrada: Date,
    fechadenacimiento: Date,
    telefono: number,
    telefonoadicional: number,
    creditodeInfonavit: string,
    estadocivil: string,
    talladeplayera:string,
    talladepantalon: string,
    pensionado: string,
    niveldeescolaridad: string,
    rol: string,
    correoelectronico: string,
    contrasena: string
}